# Generated by Django 5.2.17 on 2026-09-23 11:40

import apps.chat.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, choices=[('WONT_START', "Car won't start"), ('ENGINE_NOISE', 'Strange engine noise'), ('OVERHEATING', 'Car overheating'), ('BRAKE_PROBLEM', 'Brake problem'), ('AC_NOT_COOLING', 'AC not cooling'), ('OTHER', 'Other automotive issue')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COLLECTING', 'Collecting info'), ('READY', 'Ready for diagnosis'), ('DIAGNOSED', 'Diagnosed'), ('REJECTED', 'Out of scope'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=20)),
                ('possible_causes', models.JSONField(default=list)),
                ('overall_confidence', models.PositiveSmallIntegerField(default=0)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical / stop driving')], default='MEDIUM', max_length=10)),
                ('recommended_service', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('RULE_ENGINE', 'Backend rule engine'), ('GEMINI_ASSISTED', 'Gemini-assisted (validated)')], default='RULE_ENGINE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='chat.chatsession')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('COLLECTING', 'Collecting'), ('READY', 'Ready'), ('DIAGNOSED', 'Diagnosed')], default='COLLECTING', max_length=12)),
                ('symptoms', models.JSONField(blank=True, default=dict)),
                ('asked_question_keys', models.JSONField(blank=True, default=list)),
                ('pending_question_key', models.CharField(blank=True, max_length=40)),
                ('pending_question', models.JSONField(blank=True, default=dict)),
                ('initial_free_text', models.TextField(blank=True)),
                ('dynamic_question_count', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_state', to='chat.chatsession')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedMedia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.chat.models.upload_path)),
                ('media_type', models.CharField(choices=[('IMAGE', 'Image'), ('AUDIO', 'Audio'), ('VIDEO', 'Video')], max_length=10)),
                ('ai_analysis_summary', models.CharField(blank=True, max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='chat.chatsession')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('CUSTOMER', 'Customer'), ('BOT', 'Bot')], max_length=10)),
                ('message_type', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('SYSTEM', 'System')], default='TEXT', max_length=10)),
                ('text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatsession')),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='chat.uploadedmedia')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
